global:
  scrape_interval: 15s
  evaluation_interval: 15s

  external_labels:
    monitor: "home-server-monitor"

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: prometheus
    scrape_interval: 30s
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: node
    static_configs:
      - targets: ['prometheus-node-exporter:9100']

  - job_name: traefik
    static_configs:
      - targets: ['traefik:8082']

  # - job_name: docker
  #   static_configs:
  #     - targets: ["127.0.0.1:9323"]
  #   # https://docs.docker.com/engine/daemon/prometheus/
