# DOWNLOADING SERVICES

services:
  # ----------------------------------------
  # GLUETUN
  # Vpn client
  # ----------------------------------------
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    environment:
      - TZ=${TZ}
      - VPN_SERVICE_PROVIDER=${VPN_PROVIDER}
      - OPENVPN_USER=${VPN_USER}
      - OPENVPN_PASSWORD=${VPN_PASSWORD}
      - SERVER_REGIONS=${VPN_REGIONS}
      - DOT=on
      - DOT_PROVIDERS=cloudflare
    networks:
      - traefik_proxy
    ports:
      - ${QBITTORRENT_PORT}:8888 # qbittorrent
      - ${NZBGET_PORT}:6789 # nzbget
    volumes:
      - ../docker/volumes/htpc/gluetun:/gluetun
    devices:
      - /dev/net/tun:/dev/net/tun
    labels:
      traefik.enable: true
      traefik.docker.network: traefik_proxy
      # -- qbittorrent
      traefik.http.routers.qbittorrent.service: qbittorrent
      traefik.http.routers.qbittorrent.rule: Host(`qbittorrent.${DOMAIN}`)
      traefik.http.routers.qbittorrent.entrypoints: websecure
      traefik.http.routers.qbittorrent.tls.certresolver: myresolver
      traefik.http.services.qbittorrent.loadbalancer.server.port: 8888
      traefik.http.routers.qbittorrent.middlewares: authentik-auth
      # -- nzbget
      traefik.http.routers.nzbget.service: nzbget
      traefik.http.routers.nzbget.rule: Host(`nzbget.${DOMAIN}`)
      traefik.http.routers.nzbget.entrypoints: websecure
      traefik.http.routers.nzbget.tls.certresolver: myresolver
      traefik.http.services.nzbget.loadbalancer.server.port: 6789
      traefik.http.routers.nzbget.middlewares: authentik-auth
    restart: unless-stopped


  # ----------------------------------------
  # QBITTORRENT
  # Torrent Client
  # ----------------------------------------
  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PUID}
      - WEBUI_PORT=${QBITTORRENT_PORT}
    network_mode: 'service:gluetun' # see gluetun for traefik routing
    volumes:
      - ../docker/volumes/htpc/qbittorrent:/config
      - ${MEDIA_PATH}/torrents/Completed:/downloads
    restart: unless-stopped


  # ----------------------------------------
  # NZBGET
  # Usenet client
  # ----------------------------------------
  nzbget:
    image: lscr.io/linuxserver/nzbget:latest
    container_name: nzbget
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PUID}
      - NZBGET_USER=${NZBGET_USER}
      - NZBGET_PASS=${NZBGET_PASS}
    network_mode: 'service:gluetun' # see gluetun for traefik routing
    volumes:
      - ../docker/volumes/htpc/nzbget:/config
      - ${MEDIA_PATH}/torrents/Completed:/downloads/completed
    restart: unless-stopped


networks:
  traefik_proxy:
    external: true