# HOME THEATER PC

services:
  # ----------------------------------------
  # PROWLARR
  # Index management
  # ----------------------------------------
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    networks:
      - traefik_proxy
    ports:
      - 9696:9696
    volumes:
      - ../docker/volumes/htpc/prowlarr:/config
    labels:
      traefik.enable: true
      traefik.http.routers.prowlarr.rule: Host(`prowlarr.${DOMAIN}`)
      traefik.http.routers.prowlarr.entrypoints: websecure
      traefik.http.routers.prowlarr.tls.certresolver: myresolver
      traefik.http.routers.prowlarr.middlewares: authentik-auth
    restart: unless-stopped


  # ----------------------------------------
  # SONARR
  # TV Series Management
  # ----------------------------------------
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    networks:
      - traefik_proxy
    ports:
      - 8989:8989
    volumes:
      - ../docker/volumes/htpc/sonarr:/config
      - ${MEDIA_PATH}/media/series:/tv
      - ${MEDIA_PATH}/torrents/Completed:/downloads
    labels:
      traefik.enable: true
      traefik.http.routers.sonarr.rule: Host(`sonarr.${DOMAIN}`)
      traefik.http.routers.sonarr.entrypoints: websecure
      traefik.http.routers.sonarr.tls.certresolver: myresolver
      traefik.http.routers.sonarr.middlewares: authentik-auth
    restart: unless-stopped


  # ----------------------------------------
  # RADARR
  # Movies Management
  # ----------------------------------------
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    networks:
      - traefik_proxy
    ports:
      - 7878:7878
    volumes:
      - ../docker/volumes/htpc/radarr:/config
      - ${MEDIA_PATH}/media/movies:/movies
      - ${MEDIA_PATH}/torrents/Completed:/downloads
    labels:
      traefik.enable: true
      traefik.http.routers.radarr.rule: Host(`radarr.${DOMAIN}`)
      traefik.http.routers.radarr.entrypoints: websecure
      traefik.http.routers.radarr.tls.certresolver: myresolver
      traefik.http.routers.radarr.middlewares: authentik-auth
    restart: unless-stopped


  # ----------------------------------------
  # PLEX
  # Robust Media Server
  # ----------------------------------------
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - VERSION=docker
      - PLEX_CLAIM=${PMSTOKEN}
    networks:
      - traefik_proxy
    ports:
      - 32400:32400/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
      - 5354:5353/udp
    volumes:
      - ../docker/volumes/htpc/plex:/config
      - ../docker/volumes/htpc/plex/transcode:/transcode
      - ${MEDIA_PATH}/media/movies:/movies
      - ${MEDIA_PATH}/media/series:/tv
    labels:
      traefik.enable: true
      traefik.http.routers.plex.rule: Host(`plex.${DOMAIN}`)
      traefik.http.routers.plex.entrypoints: websecure
      traefik.http.routers.plex.tls.certresolver: myresolver
      traefik.http.services.plex.loadbalancer.server.port: 3240
      traefik.http.routers.plex.middlewares: authentik-auth

    restart: unless-stopped


networks:
  traefik_proxy:
    external: true